from collections.abc import Sequence
from typing import overload

import numpy as np
from numpy.typing import NDArray

_CoordsArray = NDArray[np.float64]
_CoordsList = Sequence[Sequence[float]]

@overload
def simplify_coords(coords: _CoordsArray, epsilon: float) -> _CoordsArray: ...
@overload
def simplify_coords(coords: _CoordsList, epsilon: float) -> list[list[float]]: ...
@overload
def simplify_coords_idx(coords: _CoordsArray, epsilon: float) -> NDArray[np.uintp]: ...
@overload
def simplify_coords_idx(coords: _CoordsList, epsilon: float) -> list[int]: ...
@overload
def simplify_coords_vw(coords: _CoordsArray, epsilon: float) -> _CoordsArray: ...
@overload
def simplify_coords_vw(coords: _CoordsList, epsilon: float) -> list[list[float]]: ...
@overload
def simplify_coords_vw_idx(
    coords: _CoordsArray, epsilon: float
) -> NDArray[np.uintp]: ...
@overload
def simplify_coords_vw_idx(coords: _CoordsList, epsilon: float) -> list[int]: ...
@overload
def simplify_coords_vwp(coords: _CoordsArray, epsilon: float) -> _CoordsArray: ...
@overload
def simplify_coords_vwp(coords: _CoordsList, epsilon: float) -> list[list[float]]: ...
